/* This test was generated by AI. */

#include <mthread/mthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <assert.h>

// Worker routine for joinable thread test
void *standard_worker(void *arg) {
	int input_val = *((int *)arg);
	printf("  [Worker] Started with arg: %d\n", input_val);

	// Test mthread_self
	mthread_handle_t self_handle = mthread_self();
	printf("  [Worker] My thread handle (mthread_self): %p\n", self_handle);

	// Test mthread_yield
	mthread_result_t yield_res = mthread_yield();
	assert(yield_res == MTHREAD_SUCCESS);

	// Test mthread_nsleep (sleep for 200 milliseconds)
	uint64_t ns_rem = mthread_nsleep(200000000ULL);
	(void)ns_rem;

	// Allocate dynamic memory to return via thread join
	int *result_ptr = malloc(sizeof(int));
	*result_ptr = input_val * 10;

	printf("  [Worker] Exiting with result: %d\n", *result_ptr);
	return (void *)result_ptr;
}

// Worker routine for testing mthread_exit and detached state
void *detached_worker(void *arg) {
	(void)arg;
	printf("  [Detached Worker] Running...\n");
	mthread_sleep(1); // Test mthread_sleep in seconds
	printf("  [Detached Worker] Calling mthread_exit explicitly.\n");
	mthread_exit(NULL); // Test mthread_exit
	return NULL; // Never reached
}

int main() {
	printf("=== STARTING COMPREHENSIVE THREAD & ATTRIBUTE TEST ===\n\n--- 1. Testing Thread Attributes ---\n");

	mthread_attr_t attr;

	// Test mthread_attr_init
	assert(mthread_attr_init(&attr) == MTHREAD_SUCCESS);
	printf("[PASS] mthread_attr_init\n");

	// Test Detach State Set/Get
	assert(mthread_attr_setdetachstate(&attr, MTHREAD_CREATE_JOINABLE) == MTHREAD_SUCCESS);
	int32_t detach_state = -1;
	assert(mthread_attr_getdetachstate(&attr, &detach_state) == MTHREAD_SUCCESS);
	assert(detach_state == MTHREAD_CREATE_JOINABLE);
	printf("[PASS] Detach State (JOINABLE) Set/Get\n");

	// Test Stack Size Set/Get
	size_t custom_stack_size = 1024 * 64; // 64 KB
	assert(mthread_attr_setstacksize(&attr, custom_stack_size) == MTHREAD_SUCCESS);
	size_t retrieved_stack_size = 0;
	assert(mthread_attr_getstacksize(&attr, &retrieved_stack_size) == MTHREAD_SUCCESS);
	assert(retrieved_stack_size == custom_stack_size);
	printf("[PASS] Stack Size Set/Get (%zu bytes)\n", retrieved_stack_size);

	// Test Guard Size Set/Get
	size_t custom_guard_size = 4096; // 4 KB page
	assert(mthread_attr_setguardsize(&attr, custom_guard_size) == MTHREAD_SUCCESS);
	size_t retrieved_guard_size = 0;
	assert(mthread_attr_getguardsize(&attr, &retrieved_guard_size) == MTHREAD_SUCCESS);
	assert(retrieved_guard_size == custom_guard_size);
	printf("[PASS] Guard Size Set/Get (%zu bytes)\n", retrieved_guard_size);

	// Test Custom Stack Address Set/Get
	// Note: pthreads require properly aligned memory buffers for custom stacks.
	long page_size = sysconf(_SC_PAGESIZE);
	void *custom_stack_addr = NULL;
	if (posix_memalign(&custom_stack_addr, page_size, custom_stack_size) == 0) {
		assert(mthread_attr_setstack(&attr, custom_stack_addr, custom_stack_size) == MTHREAD_SUCCESS);
		void *ret_stack_addr = NULL;
		size_t ret_stack_sz = 0;
		assert(mthread_attr_getstack(&attr, &ret_stack_addr, &ret_stack_sz) == MTHREAD_SUCCESS);
		assert(ret_stack_addr == custom_stack_addr);
		assert(ret_stack_sz == custom_stack_size);
		printf("[PASS] Custom Stack Address & Size Set/Get\n");
	} else {
		printf("[SKIP] Custom Stack Address allocation skipped due to posix_memalign failure\n");
	}

	// Test mthread_attr_destroy (if implemented in your wrapper)
	// assert(mthread_attr_destroy(&attr) == MTHREAD_SUCCESS);
	// printf("[PASS] mthread_attr_destroy\n");

	printf("\n--- 2. Testing Thread Lifecycle & Control ---\n");

	mthread_t thread_standard;
	int arg_val = 5;

	// Re-initialize attribute for clean creation
	mthread_attr_init(&attr);
	mthread_attr_setdetachstate(&attr, MTHREAD_CREATE_JOINABLE);

	// Test mthread_create
	printf("Main thread: Creating standard worker thread...\n");
	assert(mthread_create(&thread_standard, &attr, standard_worker, &arg_val) == MTHREAD_SUCCESS);
	printf("[PASS] mthread_create\n");

	// Test mthread_join and retrieve return value
	void *thread_retval = NULL;
	printf("Main thread: Waiting for worker thread via mthread_join...\n");
	assert(mthread_join(&thread_standard, &thread_retval) == MTHREAD_SUCCESS);
	printf("[PASS] mthread_join\n");

	if (thread_retval) {
		int result = *((int *)thread_retval);
		printf("Main thread: Joined successfully. Worker returned: %d\n", result);
		assert(result == 50);
		free(thread_retval);
	}

	// Test mthread_create with explicit detachment / mthread_detach
	mthread_t thread_detached;
	printf("Main thread: Creating thread to test manual mthread_detach...\n");
	assert(mthread_create(&thread_detached, NULL, detached_worker, NULL) == MTHREAD_SUCCESS);

	// Test mthread_detach
	assert(mthread_detach(&thread_detached) == MTHREAD_SUCCESS);
	printf("[PASS] mthread_detach\n");

	// Let the detached worker finish execution before main exits
	mthread_sleep(2);

	printf("\n=== ALL THREAD & ATTRIBUTE FUNCTIONS PASSED SUCCESSFULLY! ===\n");
	return 0;
}
